Add impl TryFrom<&[u8; 48]> for QuoteHeader
enarx/sgx pull request #13
Opened 2020-12-16 16:08 UTC by lkatalin

This PR has

- Splits `Quote` type into submodules (includes a few small fixes)
- An `impl TryFrom<&[u8; 48]> for QuoteHeader`

~~The former involved some reorganization of the code in `quote.rs` to be more organized, ex. the types now show up in the order that they go into the `Quote`. There are also header comments to help delineate these different sections. Alternatively, I could break these parts out into small submodules in separate files. Any thoughts on this?~~
Edit: there are now submodules for `quote.`

Related to: https://github.com/enarx/enarx/issues/917 ,
Related to: https://github.com/enarx/enarx/issues/84

2020-12-16 17:50 UTC, connorkuehl requested changes
Regarding the first commit: Instead of comment fences, would you consider grouping these types with submodules?

2020-12-16 17:54 UTC, lkatalin commented
@connorkuehl Yeah, sure! I'll push a new version.

2020-12-16 23:19 UTC, connorkuehl commented
Should the module structure be:

```
quote
├── header
└── sigdata
```

2020-12-17 02:19 UTC, lkatalin commented
> Should the module structure be:
> 
> ```
> quote
> ├── header
> └── sigdata
> ```

@connorkuehl That is an extremely reasonable suggestion. Updated.

2020-12-17 02:47 UTC, connorkuehl approved these changes
Looks good! 🙂

2020-12-17 07:58 UTC, haraldh approved these changes

2020-12-17 08:11 UTC, merged