docs: fix some warnings
enarx/sgx pull request #85
Opened 2022-04-05 12:09 UTC by definitelynobody

Closes #80

2022-04-07 13:45 UTC, rvolosatovs approved these changes

2022-04-11 17:05 UTC, npmccallum requested changes

2022-04-11 17:05 UTC, npmccallum commented on src/page/sinfo.rs
> +    /// Acknowledge ENCLS\[EAUG\], ENCLS\[EMODT\] and ENCLS\[EMODPR\] from the host.
Let's put them in backticks rather than escaping them.

2022-04-11 17:05 UTC, npmccallum commented on src/page/sinfo.rs
> +    /// Acknowledge ENCLS\[EAUG\] from the host.
Same as above.

2022-04-11 18:42 UTC, npmccallum approved these changes

2022-04-11 18:43 UTC, merged